// @generated by `cargo run --release --features baked-dfa-spike --example bake_dfa_gen`
// THROWAWAY SPIKE (parser-optimization spike 2026-07-03): the baked
// (goto/switch-style) scanner for the JSON bench grammar — the directly-
// executable form of the same dense DFA the live DfaScanner interprets.
// Do not edit; regenerate. Consumed (include!) by examples/baked_dfa_lex.rs.

// 68 states (incl. dead sentinel 0), 12 patterns.
/// Anchored leftmost-first match at `pos`: `(pattern id or -1, match end)`.
/// Same delayed-by-one convention as the flat-table interpreter; zero-width
/// matches rejected.
#[allow(unreachable_patterns, clippy::match_overlapping_arm, clippy::manual_range_patterns)]
pub fn match_at(bytes: &[u8], pos: usize) -> (i32, usize) {
    let len = bytes.len();
    let mut bp: i32 = -1;
    let mut be: usize = pos;
    let mut st: u32 = 1;
    let mut i = pos;
    while i < len {
        let b = bytes[i];
        st = match st {
            1 => match b { 9..=10 => 2, 12..=13 => 2, 32 => 2, 34 => 3, 43 => 4, 44 => 5, 45 => 4, 46 => 6, 48..=57 => 7, 58 => 8, 91 => 9, 93 => 10, 102 => 11, 110 => 12, 116 => 13, 123 => 14, 125 => 15, _ => 0, },
            2 => match b { 0..=8 => 16, 9..=10 => 17, 11 => 16, 12..=13 => 17, 14..=31 => 16, 32 => 17, 33..=255 => 16, _ => 0, },
            3 => match b { 0..=9 => 3, 11..=33 => 3, 34 => 18, 35..=91 => 3, 92 => 19, 93..=127 => 3, 194..=223 => 20, 224 => 21, 225..=236 => 22, 237 => 23, 238..=239 => 22, 240 => 24, 241..=243 => 25, 244 => 26, _ => 0, },
            4 => match b { 46 => 6, 48..=57 => 7, _ => 0, },
            5 => match b { 0..=255 => 27, _ => 0, },
            6 => match b { 48..=57 => 28, _ => 0, },
            7 => match b { 0..=45 => 29, 46 => 30, 47 => 29, 48..=57 => 31, 58..=68 => 29, 69 => 32, 70..=100 => 29, 101 => 32, 102..=255 => 29, _ => 0, },
            8 => match b { 0..=255 => 33, _ => 0, },
            9 => match b { 0..=255 => 34, _ => 0, },
            10 => match b { 0..=255 => 35, _ => 0, },
            11 => match b { 97 => 36, _ => 0, },
            12 => match b { 117 => 37, _ => 0, },
            13 => match b { 114 => 38, _ => 0, },
            14 => match b { 0..=255 => 39, _ => 0, },
            15 => match b { 0..=255 => 40, _ => 0, },
            16 => match b { _ => 0, },
            17 => match b { 0..=8 => 16, 9..=10 => 17, 11 => 16, 12..=13 => 17, 14..=31 => 16, 32 => 17, 33..=255 => 16, _ => 0, },
            18 => match b { 0..=255 => 41, _ => 0, },
            19 => match b { 0..=9 => 3, 11..=127 => 3, 194..=223 => 42, 224 => 43, 225..=236 => 44, 237 => 45, 238..=239 => 44, 240 => 46, 241..=243 => 47, 244 => 48, _ => 0, },
            20 => match b { 128..=191 => 3, _ => 0, },
            21 => match b { 160..=191 => 20, _ => 0, },
            22 => match b { 128..=191 => 20, _ => 0, },
            23 => match b { 128..=159 => 20, _ => 0, },
            24 => match b { 144..=191 => 22, _ => 0, },
            25 => match b { 128..=191 => 22, _ => 0, },
            26 => match b { 128..=143 => 22, _ => 0, },
            27 => match b { _ => 0, },
            28 => match b { 0..=47 => 29, 48..=57 => 49, 58..=68 => 29, 69 => 50, 70..=100 => 29, 101 => 50, 102..=255 => 29, _ => 0, },
            29 => match b { _ => 0, },
            30 => match b { 0..=47 => 29, 48..=57 => 51, 58..=68 => 29, 69 => 50, 70..=100 => 29, 101 => 50, 102..=255 => 29, _ => 0, },
            31 => match b { 0..=45 => 29, 46 => 30, 47 => 29, 48..=57 => 31, 58..=68 => 29, 69 => 32, 70..=100 => 29, 101 => 32, 102..=255 => 29, _ => 0, },
            32 => match b { 43 => 52, 45 => 52, 48..=57 => 53, _ => 0, },
            33 => match b { _ => 0, },
            34 => match b { _ => 0, },
            35 => match b { _ => 0, },
            36 => match b { 108 => 54, _ => 0, },
            37 => match b { 108 => 55, _ => 0, },
            38 => match b { 117 => 56, _ => 0, },
            39 => match b { _ => 0, },
            40 => match b { _ => 0, },
            41 => match b { _ => 0, },
            42 => match b { 128..=191 => 3, _ => 0, },
            43 => match b { 160..=191 => 42, _ => 0, },
            44 => match b { 128..=191 => 42, _ => 0, },
            45 => match b { 128..=159 => 42, _ => 0, },
            46 => match b { 144..=191 => 44, _ => 0, },
            47 => match b { 128..=191 => 44, _ => 0, },
            48 => match b { 128..=143 => 44, _ => 0, },
            49 => match b { 0..=47 => 29, 48..=57 => 49, 58..=68 => 29, 69 => 50, 70..=100 => 29, 101 => 50, 102..=255 => 29, _ => 0, },
            50 => match b { 43 => 57, 45 => 57, 48..=57 => 58, _ => 0, },
            51 => match b { 0..=47 => 29, 48..=57 => 51, 58..=68 => 29, 69 => 50, 70..=100 => 29, 101 => 50, 102..=255 => 29, _ => 0, },
            52 => match b { 48..=57 => 53, _ => 0, },
            53 => match b { 0..=47 => 29, 48..=57 => 59, 58..=255 => 29, _ => 0, },
            54 => match b { 115 => 60, _ => 0, },
            55 => match b { 108 => 61, _ => 0, },
            56 => match b { 101 => 62, _ => 0, },
            57 => match b { 48..=57 => 58, _ => 0, },
            58 => match b { 0..=47 => 29, 48..=57 => 63, 58..=255 => 29, _ => 0, },
            59 => match b { 0..=47 => 29, 48..=57 => 59, 58..=255 => 29, _ => 0, },
            60 => match b { 101 => 64, _ => 0, },
            61 => match b { 0..=255 => 65, _ => 0, },
            62 => match b { 0..=255 => 66, _ => 0, },
            63 => match b { 0..=47 => 29, 48..=57 => 63, 58..=255 => 29, _ => 0, },
            64 => match b { 0..=255 => 67, _ => 0, },
            65 => match b { _ => 0, },
            66 => match b { _ => 0, },
            67 => match b { _ => 0, },
            _ => 0,
        };
        match st {
            0 => return (bp, be),
            16 => { if i > pos { bp = 2; be = i; } }
            17 => { if i > pos { bp = 2; be = i; } }
            27 => { if i > pos { bp = 7; be = i; } }
            29 => { if i > pos { bp = 0; be = i; } }
            30 => { if i > pos { bp = 0; be = i; } }
            31 => { if i > pos { bp = 0; be = i; } }
            32 => { if i > pos { bp = 0; be = i; } }
            33 => { if i > pos { bp = 6; be = i; } }
            34 => { if i > pos { bp = 9; be = i; } }
            35 => { if i > pos { bp = 11; be = i; } }
            39 => { if i > pos { bp = 8; be = i; } }
            40 => { if i > pos { bp = 10; be = i; } }
            41 => { if i > pos { bp = 1; be = i; } }
            49 => { if i > pos { bp = 0; be = i; } }
            50 => { if i > pos { bp = 0; be = i; } }
            51 => { if i > pos { bp = 0; be = i; } }
            59 => { if i > pos { bp = 0; be = i; } }
            63 => { if i > pos { bp = 0; be = i; } }
            65 => { if i > pos { bp = 4; be = i; } }
            66 => { if i > pos { bp = 5; be = i; } }
            67 => { if i > pos { bp = 3; be = i; } }
            _ => {}
        }
        i += 1;
    }
    match st {
        2 => { if len > pos { bp = 2; be = len; } }
        5 => { if len > pos { bp = 7; be = len; } }
        7 => { if len > pos { bp = 0; be = len; } }
        8 => { if len > pos { bp = 6; be = len; } }
        9 => { if len > pos { bp = 9; be = len; } }
        10 => { if len > pos { bp = 11; be = len; } }
        14 => { if len > pos { bp = 8; be = len; } }
        15 => { if len > pos { bp = 10; be = len; } }
        17 => { if len > pos { bp = 2; be = len; } }
        18 => { if len > pos { bp = 1; be = len; } }
        28 => { if len > pos { bp = 0; be = len; } }
        30 => { if len > pos { bp = 0; be = len; } }
        31 => { if len > pos { bp = 0; be = len; } }
        49 => { if len > pos { bp = 0; be = len; } }
        51 => { if len > pos { bp = 0; be = len; } }
        53 => { if len > pos { bp = 0; be = len; } }
        58 => { if len > pos { bp = 0; be = len; } }
        59 => { if len > pos { bp = 0; be = len; } }
        61 => { if len > pos { bp = 4; be = len; } }
        62 => { if len > pos { bp = 5; be = len; } }
        63 => { if len > pos { bp = 0; be = len; } }
        64 => { if len > pos { bp = 3; be = len; } }
        _ => {}
    }
    (bp, be)
}
